Existing solutions page
uprm-inso4116-2023-2024-S1/semester-project-college-toolbox pull request #75
Opened 2023-09-25 15:31 UTC by DevSebastian1

This is what should be expected with the only difference that the descriptions are more formal and the test one has been eliminated

![image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/55168269/afa5b72b-8b36-4ebb-9895-4fb6e257486d)

2023-09-26 14:11 UTC, Poggecci requested changes
UI looks good so far, though we should probably remove the Big placeholder "Existing Solutions" at the top. 

Quick question, why are you creating all the HTML elements in the JSX component using javascript instead of just writing them into the HTML? I've never seen the pattern before and it seems unwarranted to use direct javascript DOM manipulation when React is meant to help avoid that. If you have reactive elements in the UI, prefer using Hooks and conditional rendering. Would be down to touch base with you if you have strong opinions on this.

2023-09-26 18:50 UTC, DevSebastian1 commented
> UI looks good so far, though we should probably remove the Big placeholder "Existing Solutions" at the top.
> 
> Quick question, why are you creating all the HTML elements in the JSX component using javascript instead of just writing them into the HTML? I've never seen the pattern before and it seems unwarranted to use direct javascript DOM manipulation when React is meant to help avoid that. If you have reactive elements in the UI, prefer using Hooks and conditional rendering. Would be down to touch base with you if you have strong opinions on this.

I don't have too much experience working on front end, I figured that doing it this way would make it easier to automatize the process when connected to the backend. However, if it's better practice to stick to react I am willing to make the change. On that note, what are hooks and conditional rendering?

2023-09-26 23:30 UTC, Poggecci commented
Reaching out through direct messages to discuss the topics.

2023-10-29 16:17 UTC, Poggecci approved these changes

2023-10-29 17:14 UTC, merged